### ISSUE TITLE
Further sub-divide examples section

### ISSUE THREAD

**Issue by tylerflex** [flexcompute-readthedocs/tidy3d-docs#111]

**Comment by momchil-flex** [comment]
Tyler reorganized the tutorials, we should probably sub divide the case studies too.

**Comment by tomflexcompute** [comment]
Sure I can work on it now. We are doing the knowledge base website where the case studies will be divided into categories. We can do the same categories here.

**Comment by tylerflex** [comment]
fixed by #124
