### ISSUE TITLE
Additional docs about near2far

### ISSUE THREAD

**Issue by momchil-flex** [flexcompute-readthedocs/tidy3d-docs#47]
Once the rehash of near2far is done, we should expand the documentation a bit. I just got some questions from a user that was a bit confused about things as there are many parameters and considerations. A few global points:

 - I think Near2FarKSpaceMonitor is not used anywhere in the examples right now
 - Related, I think this monitor is actually the closest to how things work in Lumerical. We should pick one of the existing Lumerical examples (e.g. https://optics.ansys.com/hc/en-us/articles/360034914733) and create something similar in our documentation, so that Lumerical users can quickly orient themselves as to how things work in Tidy3D
 - We should add some more explanations (again also based on similar documentation in Lumerical) about guidelines on how to use these types of monitors (considerations like plane vs. box, fields decaying by the boundaries, boundary conditions, exact vs non-excat projection, etc.)
 - Not exactly documentation related, but should we constrain the ux/uy in Near2FarKSpace monitor to [-1, +1]?

**Comment by shashwat-sh** [comment]
> should we constrain the ux/uy in Near2FarKSpace monitor to [-1, +1]?

Right now one would just get `nans` for any pair of ux, uy that leads to bad angles. This can already happen even if ux, uy are less than 1 in magnitude, but are such that `sqrt(ux**2 + uy**2) > 1`. We could instead check that `sqrt(ux**2 + uy**2) < 1`?

**Comment by momchil-flex** [comment]
We can't really do that since we're using a meshgrid of ux, uy. I think returning nans is ok for now at least, if we encounter some issues we may consider setting those nans to 0-s? Or maybe we should do that anyway?.

My suggesting to limit ux and uy to -1/+1 is mostly to "help" users know how these quantities should be used. For example in a typical setup you'd set both of them to a linspace between (-1, 1) and get the far field on the entire sphere. So the limit could be an extra hint in figuring this out.

**Comment by shashwat-sh** [comment]
>  we may consider setting those nans to 0-s? Or maybe we should do that anyway?

On the other hand, I wonder if the nans make it super clear what happened whereas the zeros might "fly under the radar"?

I see what you mean about [-1, 1], yeah I can add a validator for that.
